### ISSUE TITLE
Wiki「Goについて」のレビュー

### ISSUE THREAD

**Issue by Kitahat** [tanigut-study/github-slideshow#1]
レビューさせていただきました。

1. 概要について、「YouTubeもGoで書かれている」といった記述は、【使われ方】か【利用している企業】のような、別項目に詳しく記載したら良いと思いました。
2. 特徴について、階層が決まっているようでしたら、木構造の記載があると良いと思いました。
3. インストールについて、「AWS Cloud9を使用する場合は必要ない」旨の記載があると良いと思いました。
4. サンプルコードについて、表示崩れしていました。リポジトリからソースコードをcloneして実行できるようにしたら良いと思いました。
（サンプルコードの実行自体はOKでした。）
5. 資料の引用元や出典について、代表的なもののみでも、記載があるとより詳しく学習することが出来るので良いと思いました。 

確認をお願いします。

**Comment by tanigut-study** [comment]
1.Tipsとして引用説明の前に移動しました（必要に応じて詳細記載）。
3.「インストール」の見出し直下へ注記の形になるように記載しました。
5.参照・引用サイトについて追記しました。
※2, 4についてはわからなくて対応できていません。

**Comment by Kitahat** [comment]
編集していただいた部分について確認しました。OKです。

(4. )について、Wikiの表示自体が表示崩れしているということです。
マークダウンのコードブロックでこんな感じで修正していただければと存じます。
```go
package main

import "fmt"

func main() {
        fmt.Println("Hello, World")
}
```

よろしくお願いします。
